//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerDiplom
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class TransportationCost
    {
        public int IdPosition { get; set; }
        public int IdTask { get; set; }
        public int Value { get; set; }
        public int Id { get; set; }
        [JsonIgnore]
        public virtual Task Task { get; set; }
    }
}
